/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transversal_proyectog11.Vistas;

/**
 *
 * @author Ale
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuWiew
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        manuAlumno = new javax.swing.JMenu();
        itemAlumnos = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        menuInscripcion = new javax.swing.JMenu();
        itemInscripciones = new javax.swing.JMenuItem();
        menuNotas = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        manuAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/33HTRBa.png"))); // NOI18N

        itemAlumnos.setText("Formulario de Alumnos");
        itemAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlumnosActionPerformed(evt);
            }
        });
        manuAlumno.add(itemAlumnos);

        jMenuBar1.add(manuAlumno);

        menuMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tIRsMyj.png"))); // NOI18N
        jMenuBar1.add(menuMateria);

        menuInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/KBJGh0w.png"))); // NOI18N

        itemInscripciones.setText("Formulario Inscripción");
        itemInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInscripcionesActionPerformed(evt);
            }
        });
        menuInscripcion.add(itemInscripciones);

        jMenuBar1.add(menuInscripcion);

        menuNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tGeOqJ8.png"))); // NOI18N
        jMenuBar1.add(menuNotas);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/5j1MOBz.png"))); // NOI18N
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        formularioAlumnoView alumno = new formularioAlumnoView();
        alumno.setVisible(true);
        escritorio.add(alumno);
    }//GEN-LAST:event_itemAlumnosActionPerformed

    private void itemInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInscripcionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        formularioInscripcionView inscripcion = new formularioInscripcionView();
        inscripcion.setVisible(true);
        escritorio.add(inscripcion);
    }//GEN-LAST:event_itemInscripcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemAlumnos;
    private javax.swing.JMenuItem itemInscripciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu manuAlumno;
    private javax.swing.JMenu menuInscripcion;
    private javax.swing.JMenu menuMateria;
    private javax.swing.JMenu menuNotas;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
